<a href="https://colab.research.google.com/github/naeczennie/data-science-research-project---emmy-nominations/blob/main/project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

# Emmy Awards: Nominees and Winners

Since the first Emmy ceremony in 1949, the television landscape has evolved dramatically, through black-and-white broadcasts, 1950s color TV, 1960s cable expansion, and today’s dominant streaming platforms1. Throughout all these eras, the Emmy Awards, the annual television honors which recognize excellence across categories such as comedy, acting, writing, and technical achievement, have remained the preeminent awards show for the genre.
Among the three organizations overseeing the awards is the Television Academy. The Television Academy has more than 26,000 members, each belonging to one of 31 peer groups representing specific fields such as acting, directing, and writing. For nominations, all active members can vote in program categories, and peer groups vote within their categories of expertise. Before voting begins, contenders must be submitted to appear on the ballot in a specific category, and aspiring nominees must submit an episode of their best work. After nominations are announced, voters are expected to watch episode submissions on the TV Academy’s streaming platform before casting final votes, deciding on one winner per category, such as “Most Outstanding” Awards for Drama, Comedy, Directing, and Writing.
This Emmy nominations dataset reflects the evolution of the television industry by highlighting shifting trends and tastes in television.

In [ ]:
!git clone https://github.com/frontiertechinstitute/datasets.git

df = pd.read_csv('datasets/Emmy Awards and Nominees Data/emmys_original.csv')

fatal: destination path 'datasets' already exists and is not an empty directory.

,category,logo,production,type,title,distributor,producer,year,page,page_id
0,Outstanding Character Voice-Over Performance -...,https://www.emmys.com/sites/default/files/styl...,NaN,Nominee,black-ish: Election Special (Part 2),ABC,ABC,2021,0,1
1,Outstanding Character Voice-Over Performance -...,https://www.emmys.com/sites/default/files/styl...,NaN,Nominee,Bridgerton,Netflix,A Netflix Original Series in association with ...,2021,0,2
2,Outstanding Character Voice-Over Performance -...,https://www.emmys.com/sites/default/files/styl...,NaN,Nominee,Family Guy,FOX,20th Television Animation,2021,0,3
3,Outstanding Character Voice-Over Performance -...,https://www.emmys.com/sites/default/files/styl...,NaN,Nominee,Archer,FX Networks,FX Productions,2021,0,4
4,Outstanding Production Design For A Narrative ...,https://www.emmys.com/sites/default/files/styl...,"Elisabeth Williams, Production Designer",Nominee,The Handmaid's Tale,Hulu,"Hulu, MGM, Daniel Wilson Productions, The Litt...",2021,0,5

In [ ]:
!git clone https://github.com/frontiertechinstitute/datasets.git
df = pd.read_csv('datasets/emmy_cleaned.csv')

df.head()

fatal: destination path 'datasets' already exists and is not an empty directory.

,category,production,type,title,distributor,producer,year
0,Outstanding Character Voice-Over Performance -...,NaN,Nominee,black-ish: Election Special (Part 2),ABC,ABC,2021
1,Outstanding Character Voice-Over Performance -...,NaN,Nominee,Bridgerton,Netflix,A Netflix Original Series in association with ...,2021
2,Outstanding Character Voice-Over Performance -...,NaN,Nominee,Family Guy,FOX,20th Television Animation,2021
3,Outstanding Character Voice-Over Performance -...,NaN,Nominee,Archer,FX Networks,FX Productions,2021
4,Outstanding Production Design For A Narrative ...,"Elisabeth Williams, Production Designer",Nominee,The Handmaid's Tale,Hulu,"Hulu, MGM, Daniel Wilson Productions, The Litt...",2021